"""empty message

Revision ID: 1268d4900090
Revises: ba96162b8f64
Create Date: 2023-07-07 15:18:55.082573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1268d4900090'
down_revision = 'ba96162b8f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_fixed_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expenses_cents', sa.PickleType(), nullable=True))
        batch_op.drop_column('income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_fixed_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('expenses_cents')
        batch_op.drop_column('income_cents')

    # ### end Alembic commands ###
