"""adds is_fixed to categories

Revision ID: 58c9ccc27e71
Revises: 4804c97eadfa
Create Date: 2023-07-07 11:22:24.725608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c9ccc27e71'
down_revision = '4804c97eadfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fixed', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expense_category_is_fixed'), ['is_fixed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_category_is_fixed'))
        batch_op.drop_column('is_fixed')

    # ### end Alembic commands ###
