"""adds name field to budget model

Revision ID: d14a7a83b5f0
Revises: f59281dc27d1
Create Date: 2023-08-28 15:53:12.778133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14a7a83b5f0'
down_revision = 'f59281dc27d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_fixed_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_fixed_budget', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
